mbot:
    key: DISCORD_BOT_TOKEN_GOES_HERE
    cmd_prefix: m!  # This is a default value. This can also be changed on a per server basis.

db:
    type: sqlite  # This can also be set to mysql
    database: data\mbot.db  # If sqlite, this is a file path. If MYSQL, this is the db name.
    user:  # MYSQL
    password:  # MYSQL
    host:  # MYSQL

mongo:
  host: localhost
  port: 12345

# Superusers are bot admins (usually the owners) and can
# do things like reload plugins globally, etc...
superusers:
    - DISCORD_UID_OF_ADMIN_1
    - DISCORD_UID_OF_ADMIN_2
